In [20]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
import numpy as np
import SRW
from collections import Counter

# This toy example is for checking the partial derivatives

In [22]:
edges = [[0,1],[0,2],[1,2],[1,0],[2,0],[2,1]]
features = np.array([[0.9,0.1],[0.1,0.9],[0.5,0.5],[0.9,0.1],[0.1,0.9],[0.5,0.5]])
w0 = np.array([0.7,0.3])
w1 = np.array([0.7,0.300001])
rst_prob = 0.5
P_init = mutation_profile = [[1,0,0],[0,1,0],[0,1,1],[1,1,0],[1,1,1]]
nnodes = 3
group_lables = [0, 0, 1, 1, 1]
lam = 0.001

In [23]:
Q0, Q_grad = SRW.generate_Q_and_gradient(edges, nnodes, features, w0)
Q1, Q_grad1 = SRW.generate_Q_and_gradient(edges, nnodes, features, w1)

In [24]:
Q_grad

array([[[ 0.        ,  0.06602963, -0.06602963],
        [ 0.02944953,  0.        , -0.02944953],
        [-0.03676033,  0.03676033,  0.        ]],

       [[ 0.        , -0.08472869,  0.08472869],
        [-0.03864221,  0.        ,  0.03864221],
        [ 0.04631791, -0.04631791,  0.        ]]])

In [25]:
(Q1 - Q0) / 0.000001 # check

array([[ 0.        , -0.08472867,  0.08472867],
       [-0.0386422 ,  0.        ,  0.0386422 ],
       [ 0.0463179 , -0.0463179 ,  0.        ]])

In [26]:
P0 = SRW.iterative_PPR(Q0, mutation_profile, rst_prob)
P1 = SRW.iterative_PPR(Q1, mutation_profile, rst_prob)

In [27]:
P_grad = SRW.iterative_P_gradient(P0, Q0, Q_grad, rst_prob)
P_grad

array([[[ -1.37842111e-04,   1.85449268e-02,  -1.84070847e-02],
        [  4.38374474e-03,   8.16865825e-03,  -1.25524030e-02],
        [ -9.14792575e-04,   1.10144385e-02,  -1.00996460e-02],
        [  2.12295131e-03,   1.33567925e-02,  -1.54797438e-02],
        [ -6.55809087e-04,   1.35246013e-02,  -1.28687922e-02]],

       [[  4.03436264e-05,  -2.37325578e-02,   2.36922142e-02],
        [ -5.89826629e-03,  -1.04177323e-02,   1.63159986e-02],
        [  9.00786327e-04,  -1.40012357e-02,   1.31004493e-02],
        [ -2.92896133e-03,  -1.70751451e-02,   2.00041064e-02],
        [  6.13972093e-04,  -1.72450097e-02,   1.66310376e-02]]])

In [28]:
(P1 - P0) / 0.000001 # check

array([[  4.00703914e-05,  -2.37318405e-02,   2.36917700e-02],
       [ -5.89760663e-03,  -1.04185502e-02,   1.63161568e-02],
       [  9.00890473e-04,  -1.40015377e-02,   1.31006472e-02],
       [ -2.92876801e-03,  -1.70751954e-02,   2.00039634e-02],
       [  6.13950391e-04,  -1.72449720e-02,   1.66310215e-02]])

In [32]:
group2npairs = SRW.count_numbers_per_group(group_lables)

In [33]:
J0 = SRW.obj_func(P0, group_lables, group2npairs, lam, w0)
J1 = SRW.obj_func(P1, group_lables, group2npairs, lam, w1)

In [34]:
J_grad = SRW.obj_func_gradient(Q0, Q_grad, P0, P_grad, group_lables, group2npairs, lam, w0)
J_grad

array([-0.00738791,  0.01196468])

In [35]:
(J1 - J0) / 0.000001  # check

0.011963204649134696

# This toy example is for checking the gradient descent functions

In [72]:
edges = [[0,1],[0,2],[0,3],[0,4],[0,5],[1,2],[1,3],[1,4],[1,5],[2,3],[2,4],[2,5],[3,4],[3,5],[4,5],
         [1,0],[2,0],[3,0],[4,0],[5,0],[2,1],[3,1],[4,1],[5,1],[3,2],[4,2],[5,2],[4,3],[5,3],[5,4],
         [0,0],[1,1],[2,2],[3,3],[4,4],[5,5]]
features = np.array([[.9,.4,0.,1.],[.9,.6,0.,1.],[.1,.4,0.,1.],[.1,.5,0.,1.],[.1,.6,0.,1.],[.9,.5,0.,1.],[.1,.4,0.,1.],[.1,.5,0.,1.],[.1,.6,0.,1.],[.1,.4,0.,1.],[.1,.5,0.,1.],[.1,.6,0.,1.],[.9,.4,0.,1.],[.9,.6,0.,1.],[.9,.5,0.,1.],
                     [.9,.4,0.,1.],[.9,.6,0.,1.],[.1,.4,0.,1.],[.1,.5,0.,1.],[.1,.6,0.,1.],[.9,.5,0.,1.],[.1,.4,0.,1.],[.1,.5,0.,1.],[.1,.6,0.,1.],[.1,.4,0.,1.],[.1,.5,0.,1.],[.1,.6,0.,1.],[.9,.4,0.,1.],[.9,.6,0.,1.],[.9,.5,0.,1.],
                     [.0,.0,1.,1.],[.0,.0,1.,1.],[.0,.0,1.,1.],[.0,.0,1.,1.],[.0,.0,1.,1.],[.0,.0,1.,1.]])
rst_prob = 0.15
P_init = mutation_profile = [[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],
                             [0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]]
nnodes = 6
group_lables = [0, 0, 0, 1, 1, 1]
lam = 1e-8
w_init_sd = 0.01
learning_rate = 0.001

In [73]:
w = SRW.train_SRW_GD(edges, features, nnodes, P_init, rst_prob, group_lables, lam, 
                     w_init_sd, learning_rate=10, update_w_func='Nadam')

0 iteration: J is  0.0900780299463
1 iteration: J is  0.0775861599312
2 iteration: J is  0.0657291668069
3 iteration: J is  0.0657274106299
4 iteration: J is  0.0657252061215
5 iteration: J is  0.0657223966535
6 iteration: J is  0.0657187545589
7 iteration: J is  0.0657139277953
8 iteration: J is  0.0657073388621
9 iteration: J is  0.0656979734146
10 iteration: J is  0.0656838880653
11 iteration: J is  0.0656608958247
12 iteration: J is  0.0656183210259
13 iteration: J is  0.0655207844484
14 iteration: J is  0.0651817988658
15 iteration: J is  0.0620424011055
16 iteration: J is  0.0453134008127
17 iteration: J is  0.0444071713245
18 iteration: J is  0.0443791393307
19 iteration: J is  0.0443670028772
20 iteration: J is  0.0443606243165
21 iteration: J is  0.0443568207928
22 iteration: J is  0.0443542359594
23 iteration: J is  0.0443522433184
24 iteration: J is  0.0443505613168
25 iteration: J is  0.0443490732361
26 iteration: J is  0.0443477354879
27 iteration: J is  0.0443465329969
28

In [74]:
w = SRW.train_SRW_GD(edges, features, nnodes, P_init, rst_prob, group_lables, lam, 
                     w_init_sd, learning_rate=10, update_w_func='Nesterov')

0 iteration: J is  0.0899098385275
1 iteration: J is  0.0841340880411
2 iteration: J is  0.0781454281276
3 iteration: J is  0.0726877556884
4 iteration: J is  0.0682310695899
5 iteration: J is  0.0648642224801
6 iteration: J is  0.0623313216749
7 iteration: J is  0.0602962732679
8 iteration: J is  0.0585014191385
9 iteration: J is  0.0567999216544
10 iteration: J is  0.0551413110776
11 iteration: J is  0.0535422411204
12 iteration: J is  0.0520514196586
13 iteration: J is  0.0507235518283
14 iteration: J is  0.0495897413293
15 iteration: J is  0.0486535303269
16 iteration: J is  0.0478977756386
17 iteration: J is  0.0472953832756
18 iteration: J is  0.0468175601648
19 iteration: J is  0.0464382913124
20 iteration: J is  0.0461359582819
21 iteration: J is  0.0458933968075
22 iteration: J is  0.0456973045974
23 iteration: J is  0.0455374885286
24 iteration: J is  0.045406164614
25 iteration: J is  0.0452973799177
26 iteration: J is  0.0452065616531
27 iteration: J is  0.0451301755535
28 

In [75]:
w = SRW.train_SRW_GD(edges, features, nnodes, P_init, rst_prob, group_lables, lam, 
                     w_init_sd, learning_rate=10, update_w_func='Adam')

0 iteration: J is  0.0900679276818
1 iteration: J is  0.077544675187
2 iteration: J is  0.0657553810955
3 iteration: J is  0.0657610036252
4 iteration: J is  0.0657489589555
5 iteration: J is  0.0655939051256
6 iteration: J is  0.0646357862096
7 iteration: J is  0.0617984499909
8 iteration: J is  0.0585066813779
9 iteration: J is  0.0518545473039
10 iteration: J is  0.0444085831299
11 iteration: J is  0.0443996707676
12 iteration: J is  0.0444073723131
13 iteration: J is  0.0444140869867
14 iteration: J is  0.0444207648391
15 iteration: J is  0.044470372532
16 iteration: J is  0.0464474038133
17 iteration: J is  0.0453467281165
18 iteration: J is  0.0444695798524
19 iteration: J is  0.0444464437713
20 iteration: J is  0.044449435776
21 iteration: J is  0.0444528694824
22 iteration: J is  0.044456073864
23 iteration: J is  0.0444590399722
24 iteration: J is  0.0444617801997
25 iteration: J is  0.0444643078749
26 iteration: J is  0.0444666362204
27 iteration: J is  0.0444687781594
28 ite

In [76]:
w, J, d = SRW.train_SRW_BFGS(edges, features, nnodes, P_init, rst_prob, group_lables, lam, w_init_sd=0.01)

In [78]:
w, J, d

(array([ 13.48027104,   1.25285007,  -2.39613633, -10.29948304]),
 0.044335757663279553,
 {'funcalls': 13,
  'grad': array([ -8.68598694e-07,   5.51663201e-06,   8.40242750e-08,
           7.97057482e-06]),
  'nit': 12,
  'task': 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL',
  'warnflag': 0})

### Check the transition matrix Q and propagation scores P

In [79]:
Q = SRW.generate_Q(edges, nnodes, features, w)
Q

array([[  1.66347443e-06,   4.94858635e-01,   5.04743036e-01,
          1.16047683e-04,   1.31532982e-04,   1.49084059e-04],
       [  4.97186324e-01,   1.67129899e-06,   5.02413475e-01,
          1.16593541e-04,   1.32151680e-04,   1.49785312e-04],
       [  5.02130612e-01,   4.97473121e-01,   1.65486470e-06,
          1.15447049e-04,   1.30852200e-04,   1.48312437e-04],
       [  1.16053314e-04,   1.16053314e-04,   1.16053314e-04,
          1.66355515e-06,   4.94882648e-01,   5.04767529e-01],
       [  1.32151954e-04,   1.32151954e-04,   1.32151954e-04,
          4.97187355e-01,   1.67130246e-06,   5.02414517e-01],
       [  1.48304974e-04,   1.48304974e-04,   1.48304974e-04,
          5.02105343e-01,   4.97448087e-01,   1.65478142e-06]])

In [80]:
P = SRW.iterative_PPR(Q, P_init, rst_prob)
P

array([[ 0.40272573,  0.29589294,  0.29914425,  0.00073595,  0.00074206,
         0.00075906],
       [ 0.29728474,  0.40147946,  0.29899762,  0.00073632,  0.00074243,
         0.00075944],
       [ 0.29759596,  0.2960575 ,  0.40411068,  0.00073555,  0.00074165,
         0.00075865],
       [ 0.00073599,  0.00073291,  0.00073941,  0.40272996,  0.29590278,
         0.29915895],
       [ 0.00074555,  0.00074243,  0.00074902,  0.29728082,  0.40147961,
         0.29900257],
       [ 0.0007551 ,  0.00075194,  0.00075861,  0.29758116,  0.2960469 ,
         0.4041063 ]])

In [81]:
group2npairs = SRW.count_numbers_per_group(group_lables)

In [82]:
J = SRW.obj_func(P, group_lables, group2npairs, lam, w)
J

0.044335757663279553

### Compare with unweighted random walk

In [83]:
Qu = SRW.generate_Q_unweighted(edges, nnodes)
Qu

array([[ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
         0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
         0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
         0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
         0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
         0.16666667],
       [ 0.16666667,  0.16666667,  0.16666667,  0.16666667,  0.16666667,
         0.16666667]])

In [84]:
Pu = SRW.iterative_PPR(Qu, P_init, rst_prob)
Pu

array([[ 0.29166667,  0.14166667,  0.14166667,  0.14166667,  0.14166667,
         0.14166667],
       [ 0.14166667,  0.29166667,  0.14166667,  0.14166667,  0.14166667,
         0.14166667],
       [ 0.14166667,  0.14166667,  0.29166667,  0.14166667,  0.14166667,
         0.14166667],
       [ 0.14166667,  0.14166667,  0.14166667,  0.29166667,  0.14166667,
         0.14166667],
       [ 0.14166667,  0.14166667,  0.14166667,  0.14166667,  0.29166667,
         0.14166667],
       [ 0.14166667,  0.14166667,  0.14166667,  0.14166667,  0.14166667,
         0.29166667]])

In [85]:
Ju = SRW.obj_func(Pu, group_lables, group2npairs, lam, 0)
Ju

0.089999999999999941

# Scratch